[dependencies]
"wasmer/winterjs" = "^0.3.4"

[fs]
"/web" = "output/static"

[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = ["--mode", "cloudflare", "/web"]
